### ISSUE TITLE
export pose from ros bag in vdo-slam format?

### ISSUE THREAD

**Issue by colin-de** [robot-perception-group/GRADE_tools#1]
Thanks for the great work! I have an issue when exporting the output pose in vdo-slam format.
after executing
```
$ python3 src/tool/output_pose.py --type vdo_gt --path ../../datasets/gt_bags_3m/D/reindex_bags/ --topic /my_robot_0/camera/pose --output /home/Desktop/
Playing bag 75bf66e8-acb0-4f27-842d-1945ad42f9de_0.bag
Playing bag 75bf66e8-acb0-4f27-842d-1945ad42f9de_1.bag
Playing bag 75bf66e8-acb0-4f27-842d-1945ad42f9de_2.bag
Playing bag 75bf66e8-acb0-4f27-842d-1945ad42f9de_3.bag
Playing bag 75bf66e8-acb0-4f27-842d-1945ad42f9de_4.bag
Playing bag 75bf66e8-acb0-4f27-842d-1945ad42f9de_5.bag
Playing bag 75bf66e8-acb0-4f27-842d-1945ad42f9de_6.bag
Playing bag 75bf66e8-acb0-4f27-842d-1945ad42f9de_7.bag
Playing bag 75bf66e8-acb0-4f27-842d-1945ad42f9de_8.bag
Playing bag 75bf66e8-acb0-4f27-842d-1945ad42f9de_9.bag
```
I only got empty `pose_gt.txt` and empty `times.txt`.

Additionally, can we also extract groudtruth object pose from the data ros bag?

Thanks again!

**Comment by eliabntt** [comment]
Hi, 
for your issue I will check with @Kyle-Xu001 that developed specifically that code.

As for the objects poses, I can share. Please send me an email. We will make all the data available soon. We wanted to cleanse it a bit and fix a couple of issues.

**Comment by eliabntt** [comment]
JIC can you show us the output of `rosbag info ..._0.bag` ?
When did you download those bags? We are reorganizing the data in these days

**Comment by colin-de** [comment]
ok sent you an email

**Comment by eliabntt** [comment]
@Kyle-Xu001 seems that the bag has the info, so perhaps there's some typo or error in the code. 

```
$ rosbag info 75bf66e8-acb0-4f27-842d-1945ad42f9de_0.bag 
path:        75bf66e8-acb0-4f27-842d-1945ad42f9de_0.bag
version:     2.0
duration:    4.5s
start:       Jan 01 1970 01:00:00.00 (0.00)
end:         Jan 01 1970 01:00:04.47 (4.47)
size:        278.8 MB
messages:    3895
compression: none [270/270 chunks]
types:       geometry_msgs/PoseStamped [d3812c3cbc69362b77dc0b19b345f8f5]
             nav_msgs/Odometry         [cd5e73d190d741a2f92e81eda573aca7]
             sensor_msgs/CameraInfo    [c9a58c1b0b154e0e6da7578cb991d214]
             sensor_msgs/Image         [060021388200f6f0f447d0fcd9c64743]
             sensor_msgs/Imu           [6a62c6daae103f4ff57a132d6f95cec2]
             tf2_msgs/TFMessage        [94810edda583a504dfda3829e70d7eec]
topics:      /my_robot_0/camera/pose                      269 msgs    : geometry_msgs/PoseStamped
             /my_robot_0/camera_link/1/camera_info        135 msgs    : sensor_msgs/CameraInfo   
             /my_robot_0/camera_link/1/depth/image_raw    135 msgs    : sensor_msgs/Image        
             /my_robot_0/camera_link/1/rgb/image_raw      135 msgs    : sensor_msgs/Image        
             /my_robot_0/imu_body                        1073 msgs    : sensor_msgs/Imu          
             /my_robot_0/imu_camera                      1073 msgs    : sensor_msgs/Imu          
             /my_robot_0/odom                             269 msgs    : nav_msgs/Odometry        
             /tf                                          806 msgs    : tf2_msgs/TFMessage
```

@colin-de Will look into that in the next few days. I'm out for a bootcamp this week.

**Comment by eliabntt** [comment]
Hi @colin-de 

By manually looking at the code I noticed this line https://github.com/robot-perception-group/GRADE_tools/blob/171f8b90e26a3017bb35a9f4fc22c01a28b63ca6/SLAM_evaluation/src/tool/output_pose.py#L398 is hardcoded. Can you try change that /0 to /1?
/0 is going to work only for static rosbags (S, SH) while /1 for all the others. If that's it we're going to fix this.

**Comment by Kyle-Xu001** [comment]
Hi There. We have made an update to fix this problem. The problem is that some bags are missing the `"/my_robot_0/camera_link/0/rgb/image_raw"` topic. (Similarly, in rosbags such as S, SH for static scenes, they may not have the topic `"/my_robot_0/camera_link/1/rgb/image_raw"`). 

One way is as mentioned above, to manually change the /0 and /1. Another way is to pull the changes we updated.

**Comment by colin-de** [comment]
Hi! thanks for the update. pose_gt works now. 

Also interested in the object pose in the data :)
